#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/movext.h"
#include "data-mov/cltd.h"
#include "data-mov/leave.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"

#include "control-tran/ret.h"
#include "control-tran/call.h"
#include "data-mov/push.h"
#include "string/movs.h"
#include "string/cld.h"
#include "string/cmps.h"
#include "string/stos.h"
#include "string/lods.h"
#include "string/scas.h"
#include "logic/test.h"
#include "control-tran/jcc.h"
#include "control-tran/jmp.h"
#include "control-tran/bt.h"
#include "data-mov/pop.h"
#include "arith/cmp.h"
#include "arith/add.h"
#include "arith/sub.h"
#include "arith/sbb.h"
#include "arith/adc.h"

#include "logic/setb.h"
#include "logic/sete.h"
#include "logic/setne.h"
#include "logic/seto.h"
#include "logic/setp.h"
#include "logic/sets.h"